### PR TITLE
Book Downloads in iOS

### PR DESCRIPTION
**Pull request by jsubloom**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloompub-viewer-rn/25)

### CODE REVIEW

**Review by gmartin7 — CHANGES_REQUESTED** [review]
Looks good. Things are getting fancy! Just a couple of questions.

> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloompub-viewer-rn/25#-:-NJ6F0wJ3GeyHpCFrzQz:b275qag)* status: all files reviewed, 4 unresolved discussions (waiting on @sujeffreyl)

___
*[`src/components/DownloadProgressView.tsx` line 11 at r1](https://reviewable.io/reviews/bloombooks/bloompub-viewer-rn/25#-NJ69XjQ0y7WuY81sTs0:-NJ69XjQ0y7WuY81sTs1:b-igqf62) ([raw file](https://github.com/bloombooks/bloompub-viewer-rn/blob/a38aa716ff86b9d9a92653ce566bad8dfb6611ff/src/components/DownloadProgressView.tsx#L11)):*
> ```XML
>     useTheme,
> } from "react-native-paper";
> //import { Props as ProgressBarProps } from "react-native-paper/lib/typescript/components/ProgressBar";
> ```

Deleteable comment?
___
*[`src/screens/FindOnBloomLibrary.tsx` line 75 at r1](https://reviewable.io/reviews/bloombooks/bloompub-viewer-rn/25#-NJ6BtyZAKUbE_5igc5G:-NJ6BtyZAKUbE_5igc5H:b-1e4hu1) ([raw file](https://github.com/bloombooks/bloompub-viewer-rn/blob/a38aa716ff86b9d9a92653ce566bad8dfb6611ff/src/screens/FindOnBloomLibrary.tsx#L75)):*
> ```XML
>     // const host = "https://bloomlibrary.org";
>     // const host = "https://alpha.bloomlibrary.org";
>     const host = "https://dev-alpha.bloomlibrary.org";
> ```

Is this because you've had to tweak BL to send messages back to the app or something?
___
*[`src/util/Path.ts` line 15 at r1](https://reviewable.io/reviews/bloombooks/bloompub-viewer-rn/25#-NJ6ETg0AMRmyf1ujvG3:-NJ6ETg0AMRmyf1ujvG4:brr5wg) ([raw file](https://github.com/bloombooks/bloompub-viewer-rn/blob/a38aa716ff86b9d9a92653ce566bad8dfb6611ff/src/util/Path.ts#L15)):*
> ```XML
>         path: string | null | undefined,
>         extension?: string | null | undefined
>     ): string | null | undefined;
> ```

I don't understand why we need these 2 "extra" definitions. Can't you just use the last one?
___
*[`src/util/Path.ts` line 56 at r1](https://reviewable.io/reviews/bloombooks/bloompub-viewer-rn/25#-NJ6ElML90d-b00k8kod:-NJ6ElML90d-b00k8koe:b-wfec29) ([raw file](https://github.com/bloombooks/bloompub-viewer-rn/blob/a38aa716ff86b9d9a92653ce566bad8dfb6611ff/src/util/Path.ts#L56)):*
> ```XML
>     public static getFileName(path: string) {
>         const index = path.lastIndexOf("/");
>         return path.substring(index + 1);
> ```

Can `path` ever end in "/"? I think you'd get an error, if it did.

**Review by jsubloom — COMMENTED** [review]
Yes, getting quite involved now...

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloompub-viewer-rn/25#-:-NJ6Jtal3_9zxxLPwAgd:b4osmph)* status: 10 of 13 files reviewed, 4 unresolved discussions (waiting on @gmartin7)

___
*[`src/components/DownloadProgressView.tsx` line 11 at r1](https://reviewable.io/reviews/bloombooks/bloompub-viewer-rn/25#-NJ69XjQ0y7WuY81sTs0:-NJ6Gw1a69yzzMVdProX:b-896fix) ([raw file](https://github.com/bloombooks/bloompub-viewer-rn/blob/a38aa716ff86b9d9a92653ce566bad8dfb6611ff/src/components/DownloadProgressView.tsx#L11)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Deleteable comment?
</blockquote></details>

Done.
___
*[`src/screens/FindOnBloomLibrary.tsx` line 75 at r1](https://reviewable.io/reviews/bloombooks/bloompub-viewer-rn/25#-NJ6BtyZAKUbE_5igc5G:-NJ6Gy3B35XcVtjwbEEn:bacb0tw) ([raw file](https://github.com/bloombooks/bloompub-viewer-rn/blob/a38aa716ff86b9d9a92653ce566bad8dfb6611ff/src/screens/FindOnBloomLibrary.tsx#L75)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Is this because you've had to tweak BL to send messages back to the app or something?
</blockquote></details>

1) Alpha is because I tweaked BL to allow iOS to download if it was accessing the app-hosted URL.
2) dev-alpha is what I figured was the easiest way to stop inflating the download count. I guess I can keep that part local-only though.
___
*[`src/util/Path.ts` line 15 at r1](https://reviewable.io/reviews/bloombooks/bloompub-viewer-rn/25#-NJ6ETg0AMRmyf1ujvG3:-NJ6HOcH3TY4bhycZqfa:bk4o1ex) ([raw file](https://github.com/bloombooks/bloompub-viewer-rn/blob/a38aa716ff86b9d9a92653ce566bad8dfb6611ff/src/util/Path.ts#L15)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

I don't understand why we need these 2 "extra" definitions. Can't you just use the last one?
</blockquote></details>

This is like a Typescript overloading thing.
The last one is the implementation (which must be able to handle all the signatures above it).
The things above the implementation is the different function signature variations.

The reason for this is I've code it up so that you can provide either a non-null path or a possibly null path. The implementation can cover either. But if you pass in a non-null path, the return value will be "string" instead of "string | null". If we just used the last one, then your consumers would now have to check for null even though it's dumb because you know it's not null.
___
*[`src/util/Path.ts` line 56 at r1](https://reviewable.io/reviews/bloombooks/bloompub-viewer-rn/25#-NJ6ElML90d-b00k8kod:-NJ6IuzT5luR1-jVU0wB:b-2hoy8n) ([raw file](https://github.com/bloombooks/bloompub-viewer-rn/blob/a38aa716ff86b9d9a92653ce566bad8dfb6611ff/src/util/Path.ts#L56)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Can `path` ever end in "/"? I think you'd get an error, if it did.
</blockquote></details>

That's a great point, but thankfully nothing explodes. It actually returns empty string.

Maybe because of this in the substring documentaiton?
Any argument value that is less than 0 or greater than str.length is treated as if it were 0 and str.length, respectively.
Technically, my code would return str.length. But i guess if it automatically corrects values to str.length, then it makes sense that it doesn't blow up on str.length either.  Otherwise, i would've written "An error will be thrown if the argument value is greater than or equal to str.length"

**Review by jsubloom — COMMENTED** [review]
Added fix for "#" and "%" and maybe other problematic punctuation in book title. Also addresses the " " that was problematic for iOS before.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloompub-viewer-rn/25#-:-NJ6Kc9pBHwueBDkilMX:b-b1ji6o)* status: 9 of 13 files reviewed, 4 unresolved discussions (waiting on @gmartin7)

**Review by gmartin7 — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloompub-viewer-rn/25)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sujeffreyl)

___
*[`src/screens/FindOnBloomLibrary.tsx` line 75 at r1](https://reviewable.io/reviews/bloombooks/bloompub-viewer-rn/25#-NJ6BtyZAKUbE_5igc5G:-NJ6NmnRAp5-y7H-4IiL:baak9mo) ([raw file](https://github.com/bloombooks/bloompub-viewer-rn/blob/a38aa716ff86b9d9a92653ce566bad8dfb6611ff/src/screens/FindOnBloomLibrary.tsx#L75)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

1) Alpha is because I tweaked BL to allow iOS to download if it was accessing the app-hosted URL.
2) dev-alpha is what I figured was the easiest way to stop inflating the download count. I guess I can keep that part local-only though.
</blockquote></details>

OK, I was just curious. Makes sense.

**Pull request merged**
